[package]
name = "rag_system"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = { version = "0.17.1", features = ["pdf", "derive"] }
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0.94"
serde = { version = "1.0", features = ["derive"] }